name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="Terraform/templates/apps/${{ vars.MODULE }}"

      - name: Terraform Apply
        if: github.event.inputs.auto_apply == 'true'
        run: terraform apply -auto-approve -var-file="Terraform/templates/apps/${{ vars.MODULE }}"

      - name: Terraform Apply (Manual Approval)
        if: github.event.inputs.auto_apply != 'true'
        run: terraform apply -var-file="Terraform/templates/apps/${{ vars.MODULE }}"
        env:
          TF_VAR_approval: ${{ secrets.TF_VAR_APPROVAL }}